// Generated by build.py - do not edit by hand.
const VERSION='4c0ff845ed78';
const SHELL='shell-'+VERSION;
const MEDIA='media-'+VERSION;
const CORE=['index.html','aabip.html','aabip-staffing.html','aabip-info.html','manifest.webmanifest',
  'icon-192.png','icon-512.png','icon-maskable-512.png','apple-touch-icon.png','favicon.png'];

self.addEventListener('install',function(e){
  e.waitUntil(caches.open(SHELL).then(function(c){return c.addAll(CORE);})
    .then(function(){return self.skipWaiting();}));});

self.addEventListener('activate',function(e){
  e.waitUntil(caches.keys().then(function(keys){
    return Promise.all(keys.map(function(k){
      if(k!==SHELL&&k!==MEDIA)return caches.delete(k);}));
  }).then(function(){return self.clients.claim();}));});

self.addEventListener('fetch',function(e){
  var req=e.request;
  if(req.method!=='GET')return;                       // never touch sync POSTs
  var url=new URL(req.url);
  if(url.hostname==='script.google.com')return;       // sync endpoint is always live-only

  if(req.mode==='navigate'||(url.origin===location.origin&&url.pathname.endsWith('.html'))){
    // network-first so a redeploy lands, cache fallback so the booth still works offline
    e.respondWith(fetch(req).then(function(res){
      var copy=res.clone();caches.open(SHELL).then(function(c){c.put(req,copy);});return res;
    }).catch(function(){return caches.match(req).then(function(m){
      return m||caches.match('aabip.html');});}));
    return;}

  if(url.origin===location.origin){
    e.respondWith(caches.match(req).then(function(m){return m||fetch(req);}));
    return;}

  if(req.destination==='image'||/\.(jpg|jpeg|png|webp|gif)(\?|$)/i.test(url.pathname)){
    // physician photos live on ~20 hospital CDNs - cache-first, opaque responses are fine
    e.respondWith(caches.match(req).then(function(m){
      if(m)return m;
      return fetch(req).then(function(res){
        var copy=res.clone();caches.open(MEDIA).then(function(c){c.put(req,copy);});return res;
      }).catch(function(){return new Response('',{status:504});});}));}
});
